title: explaining web development
author: GitHub User
email: ajayforchrist777@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  WriYou will find everything aout web development. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
